export { default as MainPage } from "./MainPage";
export * from "./MainPage";
export { default as AboutUsPage } from "./AboutUsPage";
export * from "./AboutUsPage";
export { default as AboutDomesticViolencePage } from "./AboutDomesticViolencePage";
export * from "./AboutDomesticViolencePage";
export { default as CounselingCenterPage } from "./CounselingCenterPage";
export * from "./CounselingCenterPage";
export { default as CampaignsPage } from "./CampaignsPage";
export * from "./CampaignsPage";
export * from "./Community";
export { default as Register } from "./Register";
export * from "./Register";
